/* Bar functionality */
#include "bar_indicators.c"
#include "bar_tagicons.c"
#include "bar.c"

#include "bar_ltsymbol.c"
#include "bar_status.c"
#include "bar_tagpreview.c"
#include "bar_tags.c"
#include "bar_wintitle.c"
#include "bar_awesomebar.c"
#include "bar_systray.c"
#include "bar_wintitleactions.c"

/* Other patches */
#include "attachx.c"
#include "autostart.c"
#include "cfacts.c"
#include "dragcfact.c"
#include "exresize.c"
#include "focusdir.c"
#include "focusfollowmouse.c"
#include "movestack.c"
#include "pertag.c"
#include "placedir.c"
#include "placemouse.c"
#include "restartsig.c"
#include "rotatestack.c"
#include "togglefullscreen.c"
#include "toggletopbar.c"
#include "dragmfact.c"
/* Layouts */
#include "layout_facts.c"
#include "layout_tile.c"

