- name: Check that the nvim folder exists
  stat:
    path: "{{ lookup('env', 'HOME') }}/Descargas/.dotfiles/.config/nvim"
  register: nvim_folder
  tags: &nvim_folder_tag
    - nvim-folder

- name: "Remove neovim"
  ansible.builtin.command:
    cmd: "/usr/bin/rm -rf {{ lookup('env', 'HOME') }}/.config/nvim"
  when: nvim_folder.stat.exists == True
  tags: *nvim_folder_tag

- name: "dotfiles-nvim install"
  ansible.builtin.command:
    cmd: "/usr/bin/mv {{ lookup('env', 'HOME') }}/Descargas/.dotfiles/.config/nvim {{ lookup('env', 'HOME') }}/.config"
  when: nvim_folder.stat.exists == True
  tags: *nvim_folder_tag
